// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Only used by commands that need to replay migrations in isolation
    // (`migrate dev`, `migrate diff` against a migrations directory) - not
    // touched by `migrate deploy`, so this is safe to leave unset in
    // production.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
